CREATE TABLE PRODUCTS
(
    ID       BIGSERIAL NOT NULL,
    SEQUENCE INTEGER,
    CONSTRAINT PRODUCTS_PKEY PRIMARY KEY (ID)
);

CREATE TABLE SIZES
(
    ID         BIGSERIAL NOT NULL,
    PRODUCT_ID BIGINT    NOT NULL,
    BACK_SOON  BOOLEAN,
    SPECIAL    BOOLEAN,
    CONSTRAINT SIZES_PKEY PRIMARY KEY (ID),
    CONSTRAINT FK_PRODUCTS FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS (ID)
);

CREATE TABLE STOCKS
(
    ID       BIGSERIAL NOT NULL,
    SIZE_ID  BIGINT    NOT NULL,
    QUANTITY INTEGER,
    CONSTRAINT STOCKS_PKEY PRIMARY KEY (ID),
    CONSTRAINT FK_SIZES FOREIGN KEY (SIZE_ID) REFERENCES SIZES (ID)
);
